files_count = [
    "TCGA-ACC.htseq_counts.tsv.gz",
    "TCGA-BLCA.htseq_counts.tsv.gz",
    "TCGA-BRCA.htseq_counts.tsv.gz",
    "TCGA-CESC.htseq_counts.tsv.gz",
    "TCGA-CHOL.htseq_counts.tsv.gz",
    "TCGA-COAD.htseq_counts.tsv.gz",
    "TCGA-DLBC.htseq_counts.tsv.gz",
    "TCGA-ESCA.htseq_counts.tsv.gz",
    "TCGA-GBM.htseq_counts.tsv.gz",
    "TCGA-HNSC.htseq_counts.tsv.gz",
    "TCGA-KICH.htseq_counts.tsv.gz",
    "TCGA-KIRC.htseq_counts.tsv.gz",
    "TCGA-KIRP.htseq_counts.tsv.gz",
    "TCGA-LAML.htseq_counts.tsv.gz",
    "TCGA-LGG.htseq_counts.tsv.gz",
    "TCGA-LIHC.htseq_counts.tsv.gz",
    "TCGA-LUAD.htseq_counts.tsv.gz",
    "TCGA-LUSC.htseq_counts.tsv.gz",
    "TCGA-MESO.htseq_counts.tsv.gz",
    "TCGA-OV.htseq_counts.tsv.gz",
    "TCGA-PAAD.htseq_counts.tsv.gz",
    "TCGA-PCPG.htseq_counts.tsv.gz",
    "TCGA-PRAD.htseq_counts.tsv.gz",
    "TCGA-READ.htseq_counts.tsv.gz",
    "TCGA-SARC.htseq_counts.tsv.gz",
    "TCGA-SKCM.htseq_counts.tsv.gz",
    "TCGA-STAD.htseq_counts.tsv.gz",
    "TCGA-TGCT.htseq_counts.tsv.gz",
    "TCGA-THCA.htseq_counts.tsv.gz",
    "TCGA-THYM.htseq_counts.tsv.gz",
    "TCGA-UCEC.htseq_counts.tsv.gz",
    "TCGA-UCS.htseq_counts.tsv.gz",
    "TCGA-UVM.htseq_counts.tsv.gz"
]

files_fpkm = [
    "TCGA-ACC.htseq_fpkm.tsv.gz",
    "TCGA-BLCA.htseq_fpkm.tsv.gz",
    "TCGA-BRCA.htseq_fpkm.tsv.gz",
    "TCGA-CESC.htseq_fpkm.tsv.gz",
    "TCGA-CHOL.htseq_fpkm.tsv.gz",
    "TCGA-COAD.htseq_fpkm.tsv.gz",
    "TCGA-DLBC.htseq_fpkm.tsv.gz",
    "TCGA-ESCA.htseq_fpkm.tsv.gz",
    "TCGA-GBM.htseq_fpkm.tsv.gz",
    "TCGA-HNSC.htseq_fpkm.tsv.gz",
    "TCGA-KICH.htseq_fpkm.tsv.gz",
    "TCGA-KIRC.htseq_fpkm.tsv.gz",
    "TCGA-KIRP.htseq_fpkm.tsv.gz",
    "TCGA-LAML.htseq_fpkm.tsv.gz",
    "TCGA-LGG.htseq_fpkm.tsv.gz",
    "TCGA-LIHC.htseq_fpkm.tsv.gz",
    "TCGA-LUAD.htseq_fpkm.tsv.gz",
    "TCGA-LUSC.htseq_fpkm.tsv.gz",
    "TCGA-MESO.htseq_fpkm.tsv.gz",
    "TCGA-OV.htseq_fpkm.tsv.gz",
    "TCGA-PAAD.htseq_fpkm.tsv.gz",
    "TCGA-PCPG.htseq_fpkm.tsv.gz",
    "TCGA-PRAD.htseq_fpkm.tsv.gz",
    "TCGA-READ.htseq_fpkm.tsv.gz",
    "TCGA-SARC.htseq_fpkm.tsv.gz",
    "TCGA-SKCM.htseq_fpkm.tsv.gz",
    "TCGA-STAD.htseq_fpkm.tsv.gz",
    "TCGA-TGCT.htseq_fpkm.tsv.gz",
    "TCGA-THCA.htseq_fpkm.tsv.gz",
    "TCGA-THYM.htseq_fpkm.tsv.gz",
    "TCGA-UCEC.htseq_fpkm.tsv.gz",
    "TCGA-UCS.htseq_fpkm.tsv.gz",
    "TCGA-UVM.htseq_fpkm.tsv.gz"
]

files_fpkm_uq = [
    "TCGA-ACC.htseq_fpkm-uq.tsv.gz",
    "TCGA-BLCA.htseq_fpkm-uq.tsv.gz",
    "TCGA-BRCA.htseq_fpkm-uq.tsv.gz",
    "TCGA-CESC.htseq_fpkm-uq.tsv.gz",
    "TCGA-CHOL.htseq_fpkm-uq.tsv.gz",
    "TCGA-COAD.htseq_fpkm-uq.tsv.gz",
    "TCGA-DLBC.htseq_fpkm-uq.tsv.gz",
    "TCGA-ESCA.htseq_fpkm-uq.tsv.gz",
    "TCGA-GBM.htseq_fpkm-uq.tsv.gz",
    "TCGA-HNSC.htseq_fpkm-uq.tsv.gz",
    "TCGA-KICH.htseq_fpkm-uq.tsv.gz",
    "TCGA-KIRC.htseq_fpkm-uq.tsv.gz",
    "TCGA-KIRP.htseq_fpkm-uq.tsv.gz",
    "TCGA-LAML.htseq_fpkm-uq.tsv.gz",
    "TCGA-LGG.htseq_fpkm-uq.tsv.gz",
    "TCGA-LIHC.htseq_fpkm-uq.tsv.gz",
    "TCGA-LUAD.htseq_fpkm-uq.tsv.gz",
    "TCGA-LUSC.htseq_fpkm-uq.tsv.gz",
    "TCGA-MESO.htseq_fpkm-uq.tsv.gz",
    "TCGA-OV.htseq_fpkm-uq.tsv.gz",
    "TCGA-PAAD.htseq_fpkm-uq.tsv.gz",
    "TCGA-PCPG.htseq_fpkm-uq.tsv.gz",
    "TCGA-PRAD.htseq_fpkm-uq.tsv.gz",
    "TCGA-READ.htseq_fpkm-uq.tsv.gz",
    "TCGA-SARC.htseq_fpkm-uq.tsv.gz",
    "TCGA-SKCM.htseq_fpkm-uq.tsv.gz",
    "TCGA-STAD.htseq_fpkm-uq.tsv.gz",
    "TCGA-TGCT.htseq_fpkm-uq.tsv.gz",
    "TCGA-THCA.htseq_fpkm-uq.tsv.gz",
    "TCGA-THYM.htseq_fpkm-uq.tsv.gz",
    "TCGA-UCEC.htseq_fpkm-uq.tsv.gz",
    "TCGA-UCS.htseq_fpkm-uq.tsv.gz",
    "TCGA-UVM.htseq_fpkm-uq.tsv.gz"
]

tcga_labels = {
    'ACC': 0, 'BLCA': 1, 'BRCA': 2, 'CESC': 3, 'CHOL': 4, 'COAD': 5, 'DLBC': 6, 'ESCA': 7, 'GBM': 8,
    'HNSC': 9, 'KICH': 10, 'KIRC': 11, 'KIRP': 12, 'LAML': 13, 'LGG': 14, 'LIHC': 15, 'LUAD': 16,
    'LUSC': 17, 'MESO': 18, 'OV': 19, 'PAAD': 20, 'PCPG': 21, 'PRAD': 22, 'READ': 23, 'SARC': 24,
    'SKCM': 25, 'STAD': 26, 'TGCT': 27, 'THCA': 28, 'THYM': 29, 'UCEC': 30, 'UCS': 31, 'UVM': 32
}
